version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 8888:8888
      - 57161:1972
      - 53795:52773
      - 53773
    volumes:
      - ./:/irisdev/app